Repository sonatype-nexus-community/sonatype-platform-browser-extension, pull requests merged in 2023-07, with the labels that each got.

#12 fix: options validation and tooltips
  public/css/pagestyle.css
  public/images/sonatype-platform-spinning.gif
  src/components/Options/IQServer/IQServerOptionsPage.tsx
  src/components/Popup/IQServer/ComponentInfoPage/ComponentInfoPage.css
  src/components/Popup/IQServer/ComponentInfoPage/ComponentInfoPage.tsx
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.tsx
  src/components/Popup/Popup.css
  src/components/Popup/Popup.tsx
Labels: bug, enhancement

#21 fix: handle `repo.maven.apache.org` when no version is known #16
  src/utils/Constants.ts
Labels: bug

#20 fix: Obtain version of this extension from the manifest
  .releaserc
  package.json
  public/manifest.json
  src/components/Popup/Popup.tsx
  src/options.tsx
  src/utils/UserAgentHelper.ts
Labels: bug

#22 feat: implement histogram type view for policy violation types on all…
  docs/images/extension-open-01.png
  docs/images/extension-open-02.png
  docs/images/extension-open-03.png
  docs/images/extension-open-04.png
  docs/images/extension-open-05.png
  src/components/Popup/IQServer/ComponentInfoPage/ComponentInfoPage.tsx
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.css
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.tsx
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsPage.tsx
  src/components/Popup/Popup.css
  src/components/Popup/Popup.tsx
Labels: enhancement

#29 fix: incorrect PURL derived for RubyGems when platform was present #28
  src/utils/Constants.ts
  src/utils/PageParsing/RubyGems.test.ts
  src/utils/PageParsing/RubyGems.ts
  src/utils/PageParsing/testdata/rubygems-platform.html
Labels: bug

#32 fix: handle component match state `unknown`
  docs/images/extension-open-01.png
  public/css/pagestyle.css
  public/images/Sherlock_Trunks_sticker@300ppi.png
  public/images/sonatype-platform-icon-critical.png
  public/images/sonatype-platform-icon-low.png
  public/images/sonatype-platform-icon-moderate.png
  public/images/sonatype-platform-icon-none.png
  public/images/sonatype-platform-icon-severe.png
  public/images/sonatype-platform-icon-unspecified.png
  public/images/sonatype-platform-icon-white.png
  src/components/Popup/ExtensionPopup.tsx
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.tsx
  src/components/Popup/Popup.css
  src/components/Popup/Popup.tsx
  src/content.ts
  src/extension_service_worker.ts
  src/types/Component.ts
Labels: bug

#34 localise into French and Finnish
  docs/images/fi/extension-open-01.png
  docs/images/fr/extension-open-01.png
  public/_locales/fi/messages.json
  public/_locales/fr/messages.json
Labels: i18n

#38 Add localisation for Korean
  docs/images/ko/extension-open-01.png
  public/_locales/ko/messages.json
  src/utils/UserAgentHelper.ts
Labels: i18n

#43 fix typos in french translation
  public/_locales/de/messages.json
  public/_locales/en/messages.json
  public/_locales/fr/messages.json
  public/_locales/ko/messages.json
Labels: i18n

#44 feat: add localisation support for Portugal and Brazil (Portuguese)
  README.md
  docs/images/pt/extension-open-01.png
  public/_locales/pt_BR/messages.json
  public/_locales/pt_PT/messages.json
Labels: i18n

#41 feat: Detect IQ Server Capabilities
  public/_locales/de/messages.json
  public/_locales/en/messages.json
  public/_locales/fi/messages.json
  public/_locales/pt_BR/messages.json
  public/_locales/pt_PT/messages.json
  public/css/pagestyle.css
  public/images/Sonatype-platform-logo-white.svg
  public/images/add-on-sonatype-icon-water.png
  public/images/sonatype-firewall-icon.png
  public/images/sonatype-firewall-logo-white.svg
  public/images/sonatype-lifecycle-icon.png
  src/NexusOptionsContainer.tsx
  src/components/Help/Help.tsx
  src/components/Install/Install.tsx
  src/components/Options/General/GeneralOptionsPage.tsx
  src/components/Options/IQServer/IQServerOptionsPage.css
  src/components/Options/IQServer/IQServerOptionsPage.tsx
  src/components/Options/Options.tsx
  src/components/Popup/IQServer/LicensingPage/LicensingPage.tsx
  src/content.ts
  src/context/ExtensionConfigurationContext.ts
  src/context/ExtensionPopupContext.ts
  src/error/ExtensionError.ts
  src/extension_service_worker.ts
  src/messages/IqCapabilities.ts
  src/messages/IqMessages.ts
  src/options.tsx
  src/types/Component.ts
  src/types/ExtensionConfiguration.ts
  src/utils/Constants.ts
Labels: enhancement

#19 feat: add release process to Microsoft Edge Webstore
  .releaserc
  README.md
  package.json
  scripts/edge-webstore.js
  yarn.lock
Labels: enhancement
