Repository sonatype-nexus-community/sonatype-platform-browser-extension, pull requests merged in 2023-08, with the labels that each got.

#59 feat: add basic usage analytics collection
  .circleci/config.yml
  src/components/Options/IQServer/IQServerOptionsPage.tsx
  src/components/Options/Options.tsx
  src/content.ts
  src/extension_service_worker.ts
  src/utils/Analytics.ts
  src/utils/AnalyticsConfg.ts
Labels: enhancement

#51 localisation in Catalan and Spanish
  README.md
  docs/images/ca/extension-open-01.png
  docs/images/es/extension-open-01.png
  public/_locales/ca/messages.json
  public/_locales/es/messages.json
  src/components/Popup/Popup.tsx
Labels: i18n

#55 feat: Add example component registry links after initial connect.
  public/_locales/en/messages.json
  src/components/Options/IQServer/IQServerOptionsPage.tsx
Labels: enhancement

#49 feat: support private Sonatype Nexus Repository instances as OSS Registries
  .gitignore
  README.md
  docs/images/browse-nxrm.png
  docs/images/configure-add-nxrm.png
  public/images/sonatype-repo-icon.png
  public/manifest.json
  src/components/Options/General/GeneralOptionsPage.tsx
  src/components/Options/IQServer/IQServerOptionsPage.tsx
  src/components/Popup/ExtensionPopup.tsx
  src/content.ts
  src/extension_service_worker.ts
  src/types/Component.ts
  src/types/ExtensionConfiguration.ts
  src/utils/Constants.ts
  src/utils/Helpers.ts
  src/utils/PageParsing/NexusRepositoryPageParsing.test.ts
  src/utils/PageParsing/NexusRepositoryPageParsing.ts
  src/utils/PageParsing/testdata/nxrm3/browse-cocoapod-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-cocoapod.html
  src/utils/PageParsing/testdata/nxrm3/browse-maven2-component.html
  src/utils/PageParsing/testdata/nxrm3/browse-maven2-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-maven2.html
  src/utils/PageParsing/testdata/nxrm3/browse-npm-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-npm-no-version.html
  src/utils/PageParsing/testdata/nxrm3/browse-npm.html
  src/utils/PageParsing/testdata/nxrm3/browse-pypi-component.html
  src/utils/PageParsing/testdata/nxrm3/browse-pypi-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-pypi.html
  src/utils/PageParsing/testdata/nxrm3/browse-r-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-r-version.html
  src/utils/PageParsing/testdata/nxrm3/browse-r.html
  src/utils/PageParsing/testdata/nxrm3/browse-ruby-component.html
  src/utils/PageParsing/testdata/nxrm3/browse-ruby-folder.html
  src/utils/PageParsing/testdata/nxrm3/browse-ruby-with-platform.html
  src/utils/PageParsing/testdata/nxrm3/browse-ruby.html
  src/utils/UrlParsing.ts
Labels: enhancement

#60 feat: localisation in Chinese and Taiwanese
  README.md
  docs/images/zh_CN/extension-open-01.png
  docs/images/zh_TW/extension-open-01.png
  public/_locales/zh_CN/messages.json
  public/_locales/zh_TW/messages.json
Labels: i18n

#70 feat: localisation in Greek
  README.md
  docs/images/el/extension-open-01.png
  public/_locales/el/messages.json
Labels: i18n

#66 fix: auto-upgrade internal configuration model
  package.json
  public/manifest.json
  src/extension_service_worker.ts
  src/utils/Analytics.ts
  yarn.lock
Labels: bug

#65 fix: don't remove first application when no to fix
  src/components/Options/IQServer/IQServerOptionsPage.tsx
Labels: bug

#76 doc: add documentation about functional expectation vs Sonatype Platform
  README.md
Labels: documentation

#74 fix: update to handle URL and HTML changes for conan.io
  src/utils/Constants.ts
  src/utils/PageParsing/Conanio.test.ts
  src/utils/PageParsing/testdata/conanio-libxft-2.3.6.html
  src/utils/PageParsing/testdata/conanio-libxft-2.3.8.html
  src/utils/PageParsing/testdata/conanio-proj-8.2.1.html
  src/utils/PageParsing/testdata/update-test-data.sh
Labels: bug

#79 fix: Sonatype IQ Server URL is not visually persisted in Options
  src/components/Options/IQServer/IQServerOptionsPage.tsx
  src/extension_service_worker.ts
Labels: bug

#81 fix: #80 - fix the date formats when in between groupings
  src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.tsx
Labels: bug
